In [16]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [17]:
# Load the dataset
cars = pd.read_csv('/content/car_dekho.csv')
cars.head(4)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,seats,yeard_old,mileage_value,engine_value,max_power_value
0,Maruti Swift Dzire VDI,2014.0,450000.0,145500.0,Diesel,Individual,Manual,First Owner,5.0,11.0,23.40,1248.0,74.00
1,Skoda Rapid 1.5 TDI Ambition,2014.0,370000.0,120000.0,Diesel,Individual,Manual,Second Owner,5.0,11.0,21.14,1498.0,103.52
2,Honda City 2017-2020 EXi,2006.0,158000.0,140000.0,Petrol,Individual,Manual,Third Owner,5.0,19.0,17.70,1497.0,78.00
3,Hyundai i20 Sportz Diesel,2010.0,225000.0,127000.0,Diesel,Individual,Manual,First Owner,5.0,15.0,23.00,1396.0,90.00

In [18]:
print(cars.isnull().sum())

name               1
year               1
selling_price      1
km_driven          1
fuel               1
seller_type        1
transmission       1
owner              1
seats              1
yeard_old          1
mileage_value      1
engine_value       1
max_power_value    1
dtype: int64

In [19]:
cars = cars.dropna()

In [20]:
print(cars.isnull().sum())

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
seats              0
yeard_old          0
mileage_value      0
engine_value       0
max_power_value    0
dtype: int64

In [21]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7906 entries, 0 to 7906
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             7906 non-null   object
 1   year             7906 non-null   float64
 2   selling_price    7906 non-null   float64
 3   km_driven        7906 non-null   float64
 4   fuel             7906 non-null   object
 5   seller_type      7906 non-null   object
 6   transmission     7906 non-null   object
 7   owner            7906 non-null   object
 8   seats            7906 non-null   float64
 9   yeard_old        7906 non-null   float64
 10  mileage_value    7906 non-null   float64
 11  engine_value     7906 non-null   float64
 12  max_power_value  7906 non-null   float64
dtypes: float64(8), object(5)
memory usage: 864.7+ KB

In [22]:
cars.describe(include='number')

,year,selling_price,km_driven,seats,yeard_old,mileage_value,engine_value,max_power_value
count,7906.000000,7.906000e+03,7.906000e+03,7906.000000,7906.000000,7906.000000,7906.000000,7906.000000
mean,2013.983936,6.498137e+05,6.918866e+04,5.416393,11.016064,19.419861,1458.708829,91.587374
std,3.863695,8.135827e+05,5.679230e+04,0.959208,3.863695,4.036263,503.893057,35.747216
min,1994.000000,2.999900e+04,1.000000e+00,2.000000,5.000000,0.000000,624.000000,32.800000
25%,2012.000000,2.700000e+05,3.500000e+04,5.000000,8.000000,16.780000,1197.000000,68.050000
50%,2015.000000,4.500000e+05,6.000000e+04,5.000000,10.000000,19.300000,1248.000000,82.000000
75%,2017.000000,6.900000e+05,9.542500e+04,5.000000,13.000000,22.320000,1582.000000,102.000000
max,2020.000000,1.000000e+07,2.360457e+06,14.000000,31.000000,42.000000,3604.000000,400.000000

In [23]:
cars.describe(include='object')

                          name    fuel seller_type transmission        owner
count                     7906    7906        7906         7906         7906
unique                    1982       4           3            2            5
top     Maruti Swift Dzire VDI  Diesel  Individual       Manual  First Owner
freq                       129    4299        6563         6865         5215

In [24]:
print("=============================================")
print(cars['fuel'].value_counts())
print("=============================================")
print(cars['seller_type'].value_counts())
print("=============================================")
print(cars['transmission'].value_counts())
print("=============================================")

=============================================
fuel
Diesel    4299
Petrol    3520
CNG         52
LPG         35
Name: count, dtype: int64
=============================================
seller_type
Individual          6563
Dealer              1107
Trustmark Dealer     236
Name: count, dtype: int64
=============================================
transmission
Manual       6865
Automatic    1041
Name: count, dtype: int64
=============================================

In [25]:
# drops unnecessary columns
cars = cars.drop(['name', 'year'], axis=1)
cars.head(4)

,selling_price,km_driven,fuel,seller_type,transmission,owner,seats,yeard_old,mileage_value,engine_value,max_power_value
0,450000.0,145500.0,Diesel,Individual,Manual,First Owner,5.0,11.0,23.40,1248.0,74.00
1,370000.0,120000.0,Diesel,Individual,Manual,Second Owner,5.0,11.0,21.14,1498.0,103.52
2,158000.0,140000.0,Petrol,Individual,Manual,Third Owner,5.0,19.0,17.70,1497.0,78.00
3,225000.0,127000.0,Diesel,Individual,Manual,First Owner,5.0,15.0,23.00,1396.0,90.00

In [26]:
cars = pd.get_dummies(cars, columns=['fuel', 'seller_type', 'transmission'], drop_first=True, dtype=int)
cars.head()

,selling_price,km_driven,owner,seats,yeard_old,mileage_value,engine_value,max_power_value,fuel_Diesel,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual
0,450000.0,145500.0,First Owner,5.0,11.0,23.40,1248.0,74.00,1,0,0,1,0,1
1,370000.0,120000.0,Second Owner,5.0,11.0,21.14,1498.0,103.52,1,0,0,1,0,1
2,158000.0,140000.0,Third Owner,5.0,19.0,17.70,1497.0,78.00,0,0,1,1,0,1
3,225000.0,127000.0,First Owner,5.0,15.0,23.00,1396.0,90.00,1,0,0,1,0,1
4,130000.0,120000.0,First Owner,5.0,18.0,16.10,1298.0,88.20,0,0,1,1,0,1

In [27]:
from sklearn.preprocessing import OrdinalEncoder

# Define the desired order
owner_order = [['Fourth & Above Owner', 'Third Owner', 'Second Owner', 'First Owner', 'Test Drive Car']]

# Create encoder
oe = OrdinalEncoder(categories=owner_order)

# Apply to the DataFrame
cars[['owner']] = oe.fit_transform(cars[['owner']])

In [28]:
## For your Understanding ## Why We passing [['owner']]

# Using a Series (single bracket)
owner_series = cars['owner']
print(owner_series.shape)  # Output will be (n,) - 1D

# Using a DataFrame (double bracket)
owner_dataframe = cars[['owner']]
print(owner_dataframe.shape)  # Output will be (n, 1) - 2D

(7906,)
(7906, 1)

In [29]:
cars.head(20)

,selling_price,km_driven,owner,seats,yeard_old,mileage_value,engine_value,max_power_value,fuel_Diesel,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual
0,450000.0,145500.0,3.0,5.0,11.0,23.40,1248.0,74.00,1,0,0,1,0,1
1,370000.0,120000.0,2.0,5.0,11.0,21.14,1498.0,103.52,1,0,0,1,0,1
2,158000.0,140000.0,1.0,5.0,19.0,17.70,1497.0,78.00,0,0,1,1,0,1
3,225000.0,127000.0,3.0,5.0,15.0,23.00,1396.0,90.00,1,0,0,1,0,1
4,130000.0,120000.0,3.0,5.0,18.0,16.10,1298.0,88.20,0,0,1,1,0,1
5,440000.0,45000.0,3.0,5.0,8.0,20.14,1197.0,81.86,0,0,1,1,0,1
6,96000.0,175000.0,3.0,5.0,18.0,17.30,1061.0,57.50,0,1,0,1,0,1
7,45000.0,5000.0,2.0,4.0,24.0,16.10,796.0,37.00,0,0,1,1,0,1
8,350000.0,90000.0,3.0,5.0,14.0,23.59,1364.0,67.10,1,0,0,1,0,1
9,200000.0,169000.0,3.0,5.0,12.0,20.00,1399.0,68.10,1,0,0,1,0,1
10,500000.0,68000.0,2.0,5.0,11.0,19.01,1461.0,108.45,1,0,0,1,0,1
11,92000.0,100000.0,2.0,5.0,20.0,17.30,993.0,60.00,0,0,1,1,0,1
12,280000.0,140000.0,2.0,5.0,16.0,19.30,1248.0,73.90,1,0,0,1,0,1
13,180000.0,90000.0,2.0,5.0,16.0,18.90,1061.0,67.00,0,0,1,1,0,1
14,400000.0,40000.0,3.0,5.0,9.0,18.15,1198.0,82.00,0,0,1,1,0,1
15,778000.0,70000.0,2.0,7.0,9.0,24.52,1248.0,88.50,1,0,0,1,0,1
16,500000.0,53000.0,2.0,5.0,13.0,23.00,1396.0,90.00,1,0,0,1,0,1
17,150000.0,80000.0,2.0,5.0,23.0,19.70,796.0,46.30,0,0,1,1,0,1
18,680000.0,100000.0,3.0,5.0,9.0,22.54,1396.0,88.73,1,0,0,1,0,1
19,174000.0,100000.0,2.0,5.0,14.0,21.00,1461.0,64.10,1,0,0,1,0,1

In [30]:
x = cars.drop('selling_price', axis=1)
x.head()

,km_driven,owner,seats,yeard_old,mileage_value,engine_value,max_power_value,fuel_Diesel,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual
0,145500.0,3.0,5.0,11.0,23.40,1248.0,74.00,1,0,0,1,0,1
1,120000.0,2.0,5.0,11.0,21.14,1498.0,103.52,1,0,0,1,0,1
2,140000.0,1.0,5.0,19.0,17.70,1497.0,78.00,0,0,1,1,0,1
3,127000.0,3.0,5.0,15.0,23.00,1396.0,90.00,1,0,0,1,0,1
4,120000.0,3.0,5.0,18.0,16.10,1298.0,88.20,0,0,1,1,0,1

In [31]:
y = cars['selling_price']
y.head()

0    450000.0
1    370000.0
2    158000.0
3    225000.0
4    130000.0
Name: selling_price, dtype: float64

In [32]:
import statsmodels.api as sm
x = sm.add_constant(x)
model = sm.OLS(y, x).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          selling_price   R-squared:                       0.680
Model:                            OLS   Adj. R-squared:                  0.680
Method:                 Least Squares   F-statistic:                     1291.
Date:                Mon, 12 Jan 2026   Prob (F-statistic):               0.00
Time:                        15:14:50   Log-Likelihood:            -1.1431e+05
No. Observations:                7906   AIC:                         2.286e+05
Df Residuals:                    7892   BIC:                         2.287e+05
Df Model:                          13
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                         3.965e+05   1.16e+05      3.413      0.001    1.69e+05    6.24e+05
km_driven                       -1.0448      0.109     -9.554      0.000      -1.259      -0.830
owner                         1.607e+04   8617.860      1.865      0.062    -819.892     3.3e+04
seats                        -3.537e+04   8041.244     -4.399      0.000   -5.11e+04   -1.96e+04
yeard_old                    -3.319e+04   1919.573    -17.288      0.000   -3.69e+04   -2.94e+04
mileage_value                 1.189e+04   2150.237      5.529      0.000    7673.149    1.61e+04
engine_value                    86.1101     23.978      3.591      0.000      39.108     133.113
max_power_value               1.273e+04    261.872     48.603      0.000    1.22e+04    1.32e+04
fuel_Diesel                  -3.684e+04   6.48e+04     -0.569      0.570   -1.64e+05    9.02e+04
fuel_LPG                      1.725e+05   1.01e+05      1.701      0.089   -2.62e+04    3.71e+05
fuel_Petrol                  -8.538e+04   6.52e+04     -1.310      0.190   -2.13e+05    4.23e+04
seller_type_Individual       -2.545e+05   1.66e+04    -15.370      0.000   -2.87e+05   -2.22e+05
seller_type_Trustmark Dealer -3.621e+05   3.39e+04    -10.671      0.000   -4.29e+05   -2.96e+05
transmission_Manual           -4.62e+05   1.98e+04    -23.296      0.000   -5.01e+05   -4.23e+05
==============================================================================
Omnibus:                     4319.757   Durbin-Watson:                   1.583
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            72845.192
Skew:                           2.247   Prob(JB):                         0.00
Kurtosis:                      17.175   Cond. No.                     2.56e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.56e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [33]:
# Step 3: Split the data into training and testing sets (80% train, 20% test)
cars.head()
x = cars.drop('selling_price', axis=1)
y = cars['selling_price']

In [57]:
x.head()

,km_driven,owner,seats,yeard_old,mileage_value,engine_value,max_power_value,fuel_Diesel,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual
0,145500.0,3.0,5.0,11.0,23.40,1248.0,74.00,1,0,0,1,0,1
1,120000.0,2.0,5.0,11.0,21.14,1498.0,103.52,1,0,0,1,0,1
2,140000.0,1.0,5.0,19.0,17.70,1497.0,78.00,0,0,1,1,0,1
3,127000.0,3.0,5.0,15.0,23.00,1396.0,90.00,1,0,0,1,0,1
4,120000.0,3.0,5.0,18.0,16.10,1298.0,88.20,0,0,1,1,0,1

In [58]:
y.head()

0    450000.0
1    370000.0
2    158000.0
3    225000.0
4    130000.0
Name: selling_price, dtype: float64

In [71]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [72]:
model = LinearRegression()

In [73]:
model.fit(X_train, y_train)

LinearRegression()

In [74]:
#Make predictions on the test set
y_pred = model.predict(X_test)

In [75]:
# Evaluate using R-squared score and Mean Squared Error (MSE)
from sklearn import metrics
r2_score = model.score(X_test, y_test)
mse = metrics.root_mean_squared_error(y_test, y_pred)

print(f'R-squared: {r2_score}')
print(f'Root Mean Squared Error: {mse}')

R-squared: 0.6950234510153233
Root Mean Squared Error: 460483.46579789347

In [78]:
import numpy as np
print(np.random.rand())

0.9507143064099162

In [79]:
import numpy as np
np.random.seed(42)
print(np.random.rand())

0.3745401188473625